version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: todo_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - todo
        depends_on:
            - mysql

    nginx:
        image: nginx:latest
        container_name: todo_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - todo

    mysql:
        image: mysql:8.0
        container_name: todo_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo
            MYSQL_USER: todo
            MYSQL_PASSWORD: todo
        ports:
            - "3306:3306"
        networks:
            - todo
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: todo_phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - mysql
        networks:
            - todo

networks:
    todo:

volumes:
    db_data:
